# Generated by Django 2.2 on 2019-08-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradoresmercos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
