# Generated by Django 2.2 on 2019-07-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=30)),
                ('numeromodelo', models.CharField(default='NULL', max_length=30)),
                ('versao', models.CharField(max_length=10)),
                ('disponivel', models.BooleanField(default=True)),
                ('excluido', models.BooleanField(default=False)),
                ('ultima_alteracao', models.DateTimeField(null=True)),
            ],
        ),
    ]
