# Generated by Django 2.2 on 2019-08-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivosmercos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivos',
            name='os',
            field=models.CharField(max_length=10),
        ),
    ]
